### ISSUE TITLE
Package features development

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bpvars#11]
## Forcasting

- [x] sample from multivariate truncated normal for forecasting (all rates within `[0,100]`) #21
- [x] #28

## Plots and summaries

- [ ] #22

## Documentation and data

- [x] #20
- [x] #23

## Features 

- [x] exogenous variables in `specify_*()` and `estimate()` #12 
- [x] exogenous variables in `forecast()` #12
- [x] develop `compute_variance_decompositions.BVARPANEL` #14 
- [x] develop `plot` and `summary` for classes `ForecastsPANEL` and `PosteriorFEVDPANEL` #17 

## Models (LATER)

- [x] simplified models #34
- [x] extended model: with country groupings + country-specific fixed group allocation #10 
- [x] extended model: with estimated country groupings #10 
- [x] #29
- [x] with the missing observations treatment #36
- [x] #18 
- [x] introduce the possibility of specifying the Minnesota prior mean
