### ISSUE TITLE
exogenous variables

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bpvars#12]
Include dummy variables to accommodate how forecasting is done at the ILO. 

## todos

- [x] provide data `ilo_exogenous_variables` with dummies for `2008`, `2020`, `2021` and `ilo_exogenous_forecasts` with zeros and with documentation
- [x] exogenous variables in `specify_*()` and `specify_data_matrices()`
- [x] exogenous variables in `estimate()`
- [x] exogenous variables in `forecast()`
- [x] examples
- [x] NEWS
- [x] tests
