### ISSUE TITLE
conditional forecasting

### ISSUE THREAD

**Issue by donotdespair** [bsvars/bpvars#8]
## todos

- [x] include conditional projections for ILO data `ilo_conditional_forecast` #3
- [x] develop **cpp** function `mvnrnd_cond` for RNG from conditional mvnorm 
- [x] develop **cpp** function `forecast_conditional_bvarPANEL ` for forecasting with conditional forecasts
- [x] expand arguments in generic `forecast` bsvars/bsvars#75
- [x] implement conditional forecasting in `forecast`
- [x] double-check
- [x] documentation
- [x] testing
